exports.QueryList = {
  GET_STORE_LIST : `SELECT STORE_ID, STORE_NAME, STORE_CODE, ADDRESS FROM BMS.STORE;`,
  SAVE_NEW_STORE : `INSERT INTO BMS.STORE (STORE_NAME, STORE_CODE, ADDRESS , CREATED_BY , CREATED_ON) VALUES($1, $2, $3, $4, $5)`,
}